# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

# Terraform Specific
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.104.0
  hooks:
  - id: terraform_fmt
    files: ^terraform/.*\.tf$
  - id: terraform_validate
    files: ^terraform/.*\.tf$
  - id: terraform_tflint
    files: ^terraform/.*\.tf$
  - id: terraform_trivy
    files: ^terraform/.*\.tf$

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
    - id: shellcheck
      args: ["-x"]
      files: \.(sh|bash)$

- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.12.0-2
  hooks:
    - id: shfmt-docker
      args:
        - -i=2
        - -ci
        - -sr
        - -kp
      files: \.(sh|bash)$
