name: Terraform CI/CD
permissions:
  contents: read

on:
  push:
    paths:
      - 'terraform/**'
      - 'scripts/deployment/**'
      - '.github/workflows/terraform.yml'

env:
  PM_API_TOKEN_ID: ${{ vars.PM_API_TOKEN_ID }}
  PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN }}
  TF_VAR_cloudinit-example_root-password: ${{ secrets.CI_EXAMPLE_ROOT_PASS }}

jobs:
  terraform-plan:
    runs-on: self-hosted
    strategy:
      matrix:
        environments: ["lab"]
    environment: ${{ matrix.environments }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.HCP_API_TOKEN }}

    - name: Terraform Init ${{ matrix.environments }}
      working-directory: terraform/deployments/home-lab
      run: terraform init -input=false
      env:
        TF_WORKSPACE: ${{ matrix.environments }}

    - name: Terraform Validate ${{ matrix.environments }}
      working-directory: terraform/deployments/home-lab
      run: terraform validate

    - name: Terraform Plan ${{ matrix.environments }}
      working-directory: terraform/deployments/home-lab
      run: terraform plan -input=false -var-file=env/${{ matrix.environments }}/terraform.tfvars -out tfplan-${{ matrix.environments }}
      env:
        TF_WORKSPACE: ${{ matrix.environments }}

    - name: Upload TF Plan ${{ matrix.environments }}
      uses: actions/upload-artifact@v5
      with:
        name: tf-plan-${{ matrix.environments }}
        path: terraform/deployments/home-lab/tfplan-${{ matrix.environments }}

  terraform-apply:
    runs-on: self-hosted
    needs: terraform-plan
    strategy:
      matrix:
        environments: ["lab"]
    environment: ${{ matrix.environments }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Download TF Plan ${{ matrix.environments }}
      uses: actions/download-artifact@v6
      with:
        name: tf-plan-${{ matrix.environments }}
        path: terraform/deployments/home-lab

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.HCP_API_TOKEN }}

    - name: Terraform Init ${{ matrix.environments }}
      working-directory: terraform/deployments/home-lab
      run: terraform init -input=false
      env:
        TF_WORKSPACE: ${{ matrix.environments }}

    - name: Terraform Apply ${{ matrix.environments }}
      working-directory: terraform/deployments/home-lab
      run: terraform apply -input=false tfplan-${{ matrix.environments }}
